openapi: 3.0.3
info:
  title: Home Location Store
  description: Location store for API training course
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: "http://{host}:{port}/{basepath}"
  description: The production API server
  variables:
    host:
      description: this value can be assigned by the service provider
      default: localhost
    port:
      enum:
      - "8080"
      - "8000"
      default: "8080"
    basepath:
      default: v1
paths:
  /locations:
    get:
      description: Returns all home locations from the home location store
      operationId: locationsGET
      responses:
        "200":
          description: A list of all locations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Location'
                x-content-type: application/json
      x-swagger-router-controller: Default
    put:
      description: Update an existing location record
      operationId: locationsPUT
      requestBody:
        description: Complete home location object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
      responses:
        "200":
          description: Updated location record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        "400":
          description: Invalid Id supplied
          content: {}
        "404":
          description: Location not found
          content: {}
        "405":
          description: Invalid input
          content: {}
      x-swagger-router-controller: Default
    post:
      description: "Adds a new home location to the location store, returns the location\
        \ record"
      operationId: locationsPOST
      requestBody:
        description: Home location object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
      responses:
        "200":
          description: Worker added to store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        "405":
          description: Invalid input
          content: {}
      x-swagger-router-controller: Default
  /locations/{homeLocation}:
    get:
      description: returns a single home location record
      operationId: locationsHomeLocationGET
      parameters:
      - name: homeLocation
        in: path
        description: Name of location to search against
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: success finding location
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        "400":
          description: Invalid home location supplied
          content: {}
        "404":
          description: location not found
          content: {}
      x-swagger-router-controller: Default
    delete:
      description: deletes a single location
      operationId: locationsHomeLocationDELETE
      parameters:
      - name: homeLocation
        in: path
        description: name of home location to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: success finding location
          content: {}
        "400":
          description: Invalid Id supplied
          content: {}
        "404":
          description: location not found
          content: {}
      x-swagger-router-controller: Default
components:
  schemas:
    Location:
      required:
      - location
      - locationName
      type: object
      properties:
        locationName:
          type: string
        location:
          $ref: '#/components/schemas/GeoLocation'
      example:
        locationName: locationName
        location:
          latitude: 0.8008282
          longitude: 6.0274563
    GeoLocation:
      required:
      - latitude
      - longitude
      type: object
      properties:
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
      example:
        latitude: 0.8008282
        longitude: 6.0274563
